# Generated by Django 6.0.6 on 2026-06-25 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('programme', models.CharField(max_length=100)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('modified_at', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cerification', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('duration', models.IntegerField(null=True)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('modified_at', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.users')),
            ],
        ),
    ]
